### ISSUE TITLE
IPykernel in Poetry not recognised

### ISSUE THREAD

**Issue by nils-werner** [nteract/hydrogen#1859]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

For some reason Hydrogen does not pick up Jupyter kernels in a virtualenv that was created using [Poetry](https://python-poetry.org/).

### Steps to Reproduce

Create a `pyproject.toml` file

```toml
[tool.poetry]
name = "testbla"
version = "0.1.0"
description = ""
authors = ["Nobody <nobody@anonymous.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

install it

```
poetry install
```

And run Atom

```
poetry run atom .
```

or

```
poetry shell
atom .
```

Run a Python cell. A **No Kernels installed** message appears.

For comparison, virtualenv works:

```shell
virtualenv test; cd test
pip install jupyter
atom . 
```

### Versions

OS version:

macOS 10.15.2 Catalina using Homebrew's Python

> `atom --version`

```
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 3.7.6
git 2.24.1
```

Hydrogen version: 2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

There is no log output in the Dev Console.

### Expected behavior

Hydrogen should recognise Jupyter kernels in both plain virtualenvs and Poetry virtualenvs.
