### ISSUE TITLE
Docker proposal

### ISSUE THREAD

**Issue by MaximilianR** [nteract/hydrogen#528]
Follow up to https://github.com/nteract/hydrogen/pull/524

I think the simplest way is a dockerfile:

```dockerfile
FROM python:2
ARG TINI_VERSION=v0.10.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
RUN pip install jupyter_kernel_gateway
ENV KG_LIST_KERNELS=True
```

A docker-compose:

```yaml
version: '2'
services:
  jupyter:
    context: .
    entrypoint: ["/tini", "--"]
    command: ["jupyter", "kernelgateway", "--ip=0.0.0.0", "--port=8888"]
```

And a kernel settings default:

```
[{"name": "docker", "options": {"baseUrl": "http://localhost:8888"}}]
```

I'd propose this replaces basically all the README from L250-580. But probably I'm missing something and there's useful stuff there?

Questions:

- Do we need a docker-compose file, or should we just the commands in the dockerfile?
- Should we map the current path by default? This would allow you to run the code you're working on
- What else are we missing?
