### ISSUE TITLE
I change the Resolution of my Display,but the "hydrogen run" result looks like so small

### ISSUE THREAD

**Issue by hebijiandai** [nteract/hydrogen#547]
![1](https://cloud.githubusercontent.com/assets/5127081/21186854/f033390c-c250-11e6-80b7-a7d2391696a1.png)

I guess the problem is the ``atom UI font size``,But when I try to modify "styles.less",I don't know how to modify the ui,I only know I can modify it like this:

```css

@font-size: 14px;
html, body, .tree-view, .tab-bar .tab {
  font-size: @font-size;
}
```
How Can I solve this?It looks like so small and can't effective regonize the result.

THANKS.

**Comment by lgeiger** [comment]
Right now the font size is not easy to configure.

You can add the following to `styles.less`:
```less
.hydrogen.output-bubble .bubble-result-container pre {
  font-size: 24px;
}
```
